# Generated by Django 4.2.3 on 2023-08-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_name_menuitem_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
